# Build arguments
ARG SOURCE_CODE=.

# Builder args
ARG GIT_COMMIT=unknown
ARG GIT_TAG=unknown
ARG GIT_TREE_STATE=unknown

FROM registry.access.redhat.com/ubi9/go-toolset:1.22@sha256:703937e152d049e62f5aa8ab274a4253468ab70f7b790d92714b37cf0a140555 as builder

# Build args to be used at this step
ARG SOURCE_CODE
WORKDIR /workspace

USER root
RUN dnf install -y mailcap

COPY ${SOURCE_CODE}/go.mod .
COPY ${SOURCE_CODE}/go.sum .
COPY ${SOURCE_CODE}/ ./

# Set the /workspace directory as safe for Git
RUN git config --global --add safe.directory /workspace

RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build  GIT_COMMIT=${GIT_COMMIT} GIT_TAG=${GIT_TAG} GIT_TREE_STATE=${GIT_TREE_STATE} CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime go build  -tags strictfipsruntime -v  -o dist/workflow-controller ./cmd/workflow-controller

####################################################################################################
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:14f14e03d68f7fd5f2b18a13478b6b127c341b346c86b6e0b886ed2b7573b8e0 AS workflow-controller


ARG CI_CONTAINER_VERSION

LABEL com.redhat.component="odh-data-science-pipelines-argo-workflowcontroller-container" \
      name="managed-open-data-hub/odh-data-science-pipelines-argo-workflowcontroller-rhel8" \
      description="Argo Workflow Controller for Argo Workflows used in Data Science Pipelines" \
      summary="odh-data-science-pipelines-argo-workflowcontroller" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-data-science-pipelines-argo-workflowcontroller" \
      io.k8s.description="odh-data-science-pipelines-argo-workflowcontroller" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"

WORKDIR /bin
USER 8737
COPY --from=builder /workspace/hack/ssh_known_hosts /etc/ssh/
COPY --from=builder /workspace/hack/nsswitch.conf /etc/
COPY --chown=8737 --from=builder /workspace/dist/workflow-controller /bin/workflow-controller
ENTRYPOINT [ "/bin/workflow-controller" ]
